"""empty message

Revision ID: ac2433512127
Revises: 46944722e449
Create Date: 2022-01-03 21:02:26.184070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2433512127'
down_revision = '46944722e449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_type', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_type')
    # ### end Alembic commands ###
