"""empty message

Revision ID: f5312239d602
Revises: ac2433512127
Create Date: 2022-01-03 21:14:35.841591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5312239d602'
down_revision = 'ac2433512127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_type', sa.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
